preview = false
fix = true
unsafe-fixes = false
target-version = "py39"
line-length = 88  # consistent with blacks default
extend-exclude = ["docs", "tools", ".vscode", ".zed", ".pytest_cache", "__pycache__"]
output-format = "full"

[format]

exclude = ["*"]

[lint]

select = [
  "A",    # flake8-builtins
  "ANN",  # flake8-type-annotations
  "ARG",  # flake8-unused-arguments
  "ASYNC",# flake8-async
  "B",    # flake8-bugbear
  "BLE",  # flake8-blind-except
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "COM",  # flake8-commas
  "CPY",  # flake8-copyright
  "D",    # pydocstyle
  "DOC",  # pydoclint
  "DTZ",  # flake8-datetimez
  "E4",   # pycodestyle default
  "E7",   # pycodestyle default
  "E9",   # pycodestyle default
  "ERA",  # flake8-eradicate
  "EXE",  # flake8-executable
  "F",    # pyflakes
  "FA",   # flake8-future-annotations
  "FBT",  # flake8-boolean-trap
  "FLY",  # pyflint
  "FURB", # refurb
  "G",    # flake8-logging-format
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "INP",  # flake8-no-pep420
  "INT",  # flake8-gettext
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",    # pep8-naming
  "PERF", # perflint
  "PGH",  # pygrep-hooks
  "PIE",  # flake8-pie
  "PL",   # pylint
  "PT",   # flake8-pytest-style
  "PYI",  # flake8-pyi
  "Q",    # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # ruff
  "S",    # flake8-bandit
  "SIM",  # flake8-simpify
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "T10",  # flake8-debugger
  "T20",  # flake8-print
  "TID",  # flake8-tidy-imports
  "TC",   # flake8-type-checking
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]
ignore = [
  "ARG001",  # allow unaccessed
  "ARG002",  # allow unaccessed args
  "COM812",  # trailing comma, redundant with `black`
  "D202",    # allow blank line after function docstring
  "D203",    # no blank line before class docstring
  "D205",    # docstring summary can span more than one line
  "D401",    # docstring does not need to be imperative
  "D417",    # must be disabled for google style docs
  "ISC003", # prefer explicit string concat over implicit concat
  "N999",    # module names can be PascalCase too
  "PLR09",   # we have our own complexity rules
  "TRY003",  # error messages can be set up outside of the exception class
]
external = [ "WPS" ]

mccabe.max-complexity = 8

[lint.pydocstyle]
convention = "google"

[lint.isort]
known-first-party = ['jmaplib', 'tests']
known-local-folder = ['jmaplib', 'tests']
lines-after-imports = -1

[lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-copyright]
notice-rgx = ""

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
parametrize-values-row-type = "tuple"
parametrize-values-type = "list"

[lint.per-file-ignores]
"/**/tests/**" = [  # ignores for all test files
  "SLF001", # private accessed
  "PLR2004", # magic numbers
  "ANN",  # no type annotations in tests needed
  "N802",  # class names must be allowed as part of test function names
  "N803",  # class names must be allowed as part of fixture names
  "N806",  # class names must be allowed as part of mock names
  "TRY003",# error messages can be put directly
  "ARG005",# lambdas may have unused args
]

[lint.extend-per-file-ignores]
"/**/tests/**/test_**.py" = [  # extend ignores for test_* files, so excluding conftests
  "S101", # asserts
  "S106", # allow setting random passwords
  "F401", # unused import
  "F811", # redefinition of unused
]
